[tool.briefcase]
project_name = "Auction Plus"
bundle = "ml.llordjesse"
version = "0.0.1"
url = "https://llordjesse.ml/auctionplus"
license = "BSD license"
author = 'Jesse Amarquaye'
author_email = "llordjesse@gmail.com"

[tool.briefcase.app.auctionplus]
formal_name = "Auction Plus"
description = "Auction Plus application is a simple auction application. In this game, the goal is to beat the AI by making the highest bid. Try to become the winner of the auction. All the best."
icon = "src/auctionplus/resources/auctionplus"
sources = ['src/auctionplus']
requires = [
    
]


[tool.briefcase.app.auctionplus.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev38',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.auctionplus.linux]
requires = [
    'toga-gtk>=0.3.0.dev38',
]

[tool.briefcase.app.auctionplus.linux.appimage]
system_requires = [
    'gir1.2-webkit-3.0',
    'libcairo2-dev',
    'libgirepository1.0-dev',
    'libgtk-3-dev',
    'libpango1.0-dev',
    'librsvg2-dev',
    'libwebkitgtk-3.0-0',
]
linuxdeploy_plugins = [
    'DEPLOY_GTK_VERSION=3 gtk',
]

[tool.briefcase.app.auctionplus.linux.flatpak]
flatpak_runtime = 'org.gnome.Platform'
flatpak_runtime_version = '42'
flatpak_sdk = 'org.gnome.Sdk'

[tool.briefcase.app.auctionplus.windows]
requires = [
    'toga-winforms>=0.3.0.dev38',
]

# Mobile deployments
[tool.briefcase.app.auctionplus.iOS]
requires = [
    'toga-iOS>=0.3.0.dev38',
    'std-nslog~=1.0.0'
]

[tool.briefcase.app.auctionplus.android]
requires = [
    'toga-android>=0.3.0.dev38'
]

[tool.briefcase.app.auctionplus.web]
requires = [
    # Workaround; toga-web 0.3.0.dev38 doesn't include toga-core as a dependency.
    "toga-core>=0.3.0.dev38",
    "toga-web>=0.3.0.dev38",
]
style_framework = "Bootstrap v4.6"
